spring:
  profiles:
    active: production
  datasource:
    url: jdbc:postgresql://localhost:5432/coloc
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/coloc-app
server:
  port: 8081
jwt:
  auth:
    converter:
      resource-id: coloc-app-client
